spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/top-100-crypto
      host: localhost
      port: 27017
      database: top-100-crypto

cmc:
  api:
    key: 745b7d68-e21b-4776-8adb-6e7359739b44

logging:
  level:
    root: INFO
    org:
      springframework:
        web:
          socket: DEBUG
      apache:
        tomcat:
          websocket: DEBUG

